### ISSUE TITLE
Script keybindings deactivated after playing any selection from a playlist with mpv 0.33

### ISSUE THREAD

**Issue by gbstan** [gthreepw00d/mpv-iptv#3]
With the new mpv 0.33, when playing a selected entry in a playlist (selecting an entry and then pressing enter), the keybindings defined at the beginning of the script iptv.lua are deactivated and the interface cannot be called again.

I do not know lua and was wondering if there is a simple change to iptv.lua that would allow to call again the interface for selecting a different entry once a file is already playing.

This seems to be linked to an issue on in the definition of the function play.

[iptv] stack traceback:
[iptv] 	[string "/Users/guy-bartstan/.config/mpv/scripts/ipt..."]:340: in function 'play'
[iptv] 	[string "/Users/guy-bartstan/.config/mpv/scripts/ipt..."]:482: in function 'fn'
[iptv] 	mp.defaults:230: in function 'fn'
[iptv] 	mp.defaults:65: in function 'handler'
[iptv] 	mp.defaults:370: in function 'handler'
[iptv] 	mp.defaults:500: in function 'call_event_handlers'
[iptv] 	mp.defaults:534: in function 'dispatch_events'
[iptv] 	mp.defaults:493: in function <mp.defaults:492>
[iptv] 	[C]: ?
[iptv] 	[C]: ?
[iptv] Lua error: [string "/Users/guy-bartstan/.config/mpv/scripts/ipt..."]:340: attempt to index field '?' (a nil value)

**Comment by gbstan** [comment]
To fix the issue, one just needs to comment out a part of the function play (the if statement in the code of the play function):
play = function(self)
    mp.commandv("loadfile",self.pls[self.plsfiltered[self.wndstart+self.cursor]].filename)
    -- if (self.plspos) then
    --   self.pls[self.plspos].current=false
    -- end
    self.plspos=self.plsfiltered[self.wndstart+self.cursor]
    self.pls[self.plspos].current=true
  end

**Comment by gthreepw00d** [comment]
Should be fixed now.

**Comment by LampPrinter** [comment]
Same issue again in mpv 0.35
